name: kweeksnews_app
description: Flutter app for KweeksNews site

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  dio_http_cache: ^0.2.6
  email_validator: ^1.0.6
  firebase_analytics: ^7.0.1
  firebase_core: ^1.0.0
  flutter_html: ^1.0.2
  flutter_riverpod: ^0.12.4
  fluttertoast: ^7.1.8
  font_awesome_flutter: ^8.11.0
  html_unescape: ^1.0.2
  infinite_scroll_pagination: ^3.0.0
  intl: ^0.17.0
  moor: ^3.4.0
  moor_flutter: ^3.1.0
  package_info: ^2.0.0
  path_provider: ^2.0.0-nullsafety
  share: ^0.6.5+1
  shared_preferences: ^2.0.0-nullsafety.1
  shimmer: ^1.1.2
  sqlite3_flutter_libs: ^0.4.0+1
  url_launcher: ^6.0.2
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: null
  flutter_launcher_icons: ^0.8.1
  lint: ^1.5.2
  moor_generator: ^3.4.0

flutter_icons:
  image_path: assets/ic_launcher.png
  adaptive_icon_background: "#FF000000"
  android: "ic_launcher"
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/error.png
    - assets/no_data.png
    - assets/placeholder.png
    - assets/search.png
    - assets/dark/icon.png
    - assets/light/icon.png

  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri/Amiri-Bold.ttf
        - asset: fonts/Amiri/Amiri-BoldItalic.ttf
        - asset: fonts/Amiri/Amiri-Italic.ttf
        - asset: fonts/Amiri/Amiri-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf

    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
        - asset: fonts/Quicksand/Quicksand-Light.ttf
        - asset: fonts/Quicksand/Quicksand-Medium.ttf
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
        - asset: fonts/Quicksand/Quicksand-SemiBold.ttf
